- name: Provision VM in Azure
  hosts: localhost
  connection: local
  vars_files:
    - ../inventories/lab.yml
  tasks:
    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: iac-lab-rg
        name: azure_vm1
        vm_size: Standard_B1s
        admin_username: azureuser
        admin_password: ChangeMe123!
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: 22.04-LTS
          version: latest
